name: Publish to Docker

on:
  push:
    branches:
      - main  # main ブランチに push されたら実行

permissions:
  packages: write  # GitHub Packages への書き込み権限
  contents: read   # リポジトリの読み取り権限

jobs:
  publish:
    runs-on: ubuntu-latest  # 最新の Ubuntu 環境で実行

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # リポジトリのコードを取得

      # メタデータの生成（Docker イメージの名前とタグを設定）
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/seine1499/publish-packages/game  # YOURNAME を GitHub ユーザー名に変更
          tags: type=sha  # コミット SHA をタグにする

      # GitHub Container Registry にログイン
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Docker イメージをビルドしてプッシュ
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
